variables:
  PLATFORM_MIN_VERSION: '6.6.0.0'
  PLATFORM_DEFAULT_VERSION: 'trunk'
  PLATFORM_BRANCH: $PLATFORM_DEFAULT_VERSION
  CMS_EXTENSION_BRANCH: 'master'
  COMMERCIAL_ENABLED: 'true'
  DEPENDENCIES_WITHOUT_COMMERCIAL: |
    [{ "name": "SwagCmsExtensions", "url": "gitlab.shopware.com/shopware/6/services/cms-extensions", "branch": "$CMS_EXTENSION_BRANCH" }]
  DEPENDENCIES_WITH_COMMERCIAL: |
    [
      { "name": "SwagCmsExtensions", "url": "gitlab.shopware.com/shopware/6/services/cms-extensions", "branch": "$CMS_EXTENSION_BRANCH" },
      { "name": "SwagCommercial", "url": "gitlab.shopware.com/shopware/6/product/commercial.git", "branch": "$PLATFORM_BRANCH" }
    ]
  PLUGIN_DEPENDENCIES: $DEPENDENCIES_WITH_COMMERCIAL

phpunit:
  services:
    -   name: $MYSQL_IMAGE
        alias: database
        entrypoint: [ 'sh', '-c', "docker-entrypoint.sh $MYSQL_CMD" ]
  script:
    -   composer dump-autoload --dev -d "${PROJECT_ROOT}/custom/plugins/${PLUGIN_NAME}"
    -   php
        -d pcov.enabled=1 -d pcov.directory=$PWD/src -d pcov.exclude='~(vendor|tests|node_modules)~'
        ${PROJECT_ROOT}/vendor/bin/phpunit
        --configuration phpunit.xml.dist
        --log-junit ${CI_PROJECT_DIR}/phpunit.junit.xml
        --colors=never
        --coverage-cobertura ${CI_PROJECT_DIR}/cobertura.xml
        --coverage-text | grep -v -E '^Shopware\\|^  Methods:' # do not output covered files lines
  parallel:
    matrix:
      -   MYSQL_IMAGE:
            - mysql:8.0
          DEV_IMAGE: [ 'shopware/development:8.2-composer-2', 'shopware/development:8.3-composer-2' ]
          MYSQL_CMD: $MYSQL8_CMD
          # PLATFORM_BRANCH: [ $PLATFORM_MIN_VERSION, $PLATFORM_DEFAULT_VERSION ]
          PLUGIN_DEPENDENCIES: [ $DEPENDENCIES_WITH_COMMERCIAL, $DEPENDENCIES_WITHOUT_COMMERCIAL ]
      -   MYSQL_IMAGE:
            - mariadb:10.11
          DEV_IMAGE: [ 'shopware/development:8.2-composer-2', 'shopware/development:8.3-composer-2' ]
          # PLATFORM_BRANCH: [ $PLATFORM_MIN_VERSION, $PLATFORM_DEFAULT_VERSION ]
          PLUGIN_DEPENDENCIES: [ $DEPENDENCIES_WITH_COMMERCIAL, $DEPENDENCIES_WITHOUT_COMMERCIAL ]

phpstan:
  script:
    - composer dump-autoload --dev -d "${PROJECT_ROOT}/custom/plugins/SwagCmsExtensions"
    - composer phpstan
  parallel:
    matrix:
      -   DEV_IMAGE: [ 'shopware/development:8.2-composer-2', 'shopware/development:8.3-composer-2' ]
          # PLATFORM_BRANCH: [ $PLATFORM_MIN_VERSION, $PLATFORM_DEFAULT_VERSION ]

eslint (administration):
  stage: test
  needs: []
  rules:
    - changes:
        - 'src/Resources/app/administration/**/*'
  script:
    - $CI_PROJECT_DIR/bin/console bundle:dump
    - npm ci --prefix $CI_PROJECT_DIR/src/Administration/Resources/app/administration --no-audit --prefer-offline
    - composer init:admin
    - composer lint:admin:ci

eslint (storefront):
  stage: test
  needs: []
  rules:
    - changes:
        - 'src/Resources/app/storefront/**/*'
  script:
    - $CI_PROJECT_DIR/bin/console bundle:dump
    - npm ci --prefix $CI_PROJECT_DIR/src/Storefront/Resources/app/storefront --no-audit --prefer-offline
    - composer init:storefront
    - composer lint:storefront:ci

build and validate zip:
  after_script:
    - mv ${PLUGIN_NAME}.zip ${PLUGIN_NAME}_untouched.zip
    - unzip ${PLUGIN_NAME}_untouched.zip -d ${PLUGIN_NAME}
    - find . -type f -exec touch {} +
    - apt-get update && apt-get install -y zip gzip
    - zip -r ${PLUGIN_NAME}.zip ${PLUGIN_NAME}

include:
  project: 'shopware/6/product/platform'
  ref: 'trunk'
  file: '.gitlab/templates/plugin.yml'
